const DUMMY_BOARD_DATA = [
  {
    id: 1,
    card_id: [1, 2, 3, 4],
    user_id: 1,
    date_created: "24",
    board_title: "Capstone Inspo",
    board_owner: "Anna",
    visible: true,
  },
  {
    id: 2,
    card_id: [1, 2, 3, 4, 5, 6],
    user_id: 8,
    date_created: "25",
    board_title: "Interview Inspo",
    board_owner: "Emily",
    visible: true,
  },
  {
    id: 3,
    card_id: [1],
    user_id: 6,
    date_created: "26",
    board_title: "Ada Fun",
    board_owner: "Kumi",
    visible: true,
  },
  {
    id: 4,
    card_id: [],
    user_id: 15,
    date_created: "27",
    board_title: "React excitement",
    board_owner: "Katherine",
    visible: true,
  },
  {
    id: 5,
    card_id: [1, 2, 3, 4],
    user_id: 1,
    date_created: "24",
    board_title: "Capstone Inspo",
    board_owner: "Anna",
    visible: true,
  },
  {
    id: 6,
    card_id: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    user_id: 8,
    date_created: "25",
    board_title: "Interview Inspo",
    board_owner: "Emily",
    visible: true,
  },
  {
    id: 7,
    card_id: [1, 2, 3],
    user_id: 6,
    date_created: "26",
    board_title: "Ada Fun",
    board_owner: "Kumi",
    visible: true,
  },
  // {
  //   id: 8,
  //   card_id: [1, 2, 3, 4, 5],
  //   user_id: 15,
  //   date_created: "27",
  //   board_title: "React excitement",
  //   board_owner: "Katherine",
  //   visible: true,
  // },
  // {
  //   id: 9,
  //   card_id: [16, 2, 53],
  //   user_id: 1,
  //   date_created: "24",
  //   board_title: "Capstone Inspo",
  //   board_owner: "Anna",
  //   visible: true,
  // },
  // {
  //   id: 10,
  //   card_id: [1, 2],
  //   user_id: 8,
  //   date_created: "25",
  //   board_title: "Interview Inspo",
  //   board_owner: "Emily",
  //   visible: true,
  // },
  // {
  //   id: 11,
  //   card_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 100],
  //   user_id: 6,
  //   date_created: "26",
  //   board_title: "Ada Fun",
  //   board_owner: "Kumi",
  //   visible: true,
  // },
  // {
  //   id: 12,
  //   card_id: [1, 2, 3, 4, 5, 6, 7],
  //   user_id: 15,
  //   date_created: "27",
  //   board_title: "React excitement",
  //   board_owner: "Katherine",
  //   visible: true,
  // },
  // {
  //   id: 13,
  //   card_id: [],
  //   user_id: 1,
  //   date_created: "24",
  //   board_title: "Capstone Inspo",
  //   board_owner: "Anna",
  //   visible: true,
  // },
  // {
  //   id: 14,
  //   card_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  //   user_id: 8,
  //   date_created: "25",
  //   board_title: "Interview Inspo",
  //   board_owner: "Emily",
  //   visible: true,
  // },
  // {
  //   id: 15,
  //   card_id: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  //   user_id: 6,
  //   date_created: "26",
  //   board_title: "Ada Fun",
  //   board_owner: "Kumi",
  //   visible: true,
  // },
  // {
  //   id: 16,
  //   card_id: [10, 9, 8, 7, 6, 5],
  //   user_id: 15,
  //   date_created: "27",
  //   board_title: "React excitement",
  //   board_owner: "Katherine",
  //   visible: true,
  // },
];

const DUMMY_CARD_DATA = [
  {
    id: 1,
    user_id: 1, 
    message: "You are amazing!", 
    likes: 2, 
    date_created: 1/15/23
  },
  {
    id: 2,
    user_id: 3, 
    message: "It is never too late to have a good day", 
    likes: 5, 
    date_created: 1/13/23
  },
  {
    id: 3,
    user_id: 3, 
    message: "Great job on your interviews", 
    likes: 6, 
    date_created: 1/13/23
  },
  {
    id: 4,
    user_id: 3, 
    message: "The future is no place to place your better days", 
    likes: 5, 
    date_created: 1/13/23
  },
  {
    id: 5,
    user_id: 3, 
    message: "Channel that mediocre cishet white man energy! You can do anything!", 
    likes: 5, 
    date_created: 1/13/23
  },
  {
    id: 6,
    user_id: 3, 
    message: "You are not a bad person just b/c you are kinda bad at CSS", 
    likes: 5, 
    date_created: 1/13/23
  },
  {
    id: 7,
    user_id: 3, 
    message: "You are for sure as smart as Ansel", 
    likes: 5, 
    date_created: 1/13/23
  }
]

export default DUMMY_BOARD_DATA;

